'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Class Idioma
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Steam_Skins.Idioma", GetType(Idioma).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Back.
        '''</summary>
        Friend Shared ReadOnly Property back() As String
            Get
                Return ResourceManager.GetString("back", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Dots.
        '''</summary>
        Friend Shared ReadOnly Property backgroundDots() As String
            Get
                Return ResourceManager.GetString("backgroundDots", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Noise.
        '''</summary>
        Friend Shared ReadOnly Property backgroundNoise() As String
            Get
                Return ResourceManager.GetString("backgroundNoise", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to None.
        '''</summary>
        Friend Shared ReadOnly Property backgroundNone() As String
            Get
                Return ResourceManager.GetString("backgroundNone", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Ribbon.
        '''</summary>
        Friend Shared ReadOnly Property backgroundRibbon() As String
            Get
                Return ResourceManager.GetString("backgroundRibbon", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Delete all installed skins.
        '''</summary>
        Friend Shared ReadOnly Property buttonCleanAllSkins() As String
            Get
                Return ResourceManager.GetString("buttonCleanAllSkins", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Checking the last version.
        '''</summary>
        Friend Shared ReadOnly Property checkingLastVersion() As String
            Get
                Return ResourceManager.GetString("checkingLastVersion", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Black.
        '''</summary>
        Friend Shared ReadOnly Property colorBlack() As String
            Get
                Return ResourceManager.GetString("colorBlack", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Blue.
        '''</summary>
        Friend Shared ReadOnly Property colorBlue() As String
            Get
                Return ResourceManager.GetString("colorBlue", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Breeze.
        '''</summary>
        Friend Shared ReadOnly Property colorBreeze() As String
            Get
                Return ResourceManager.GetString("colorBreeze", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Bubblegum.
        '''</summary>
        Friend Shared ReadOnly Property colorBubblegum() As String
            Get
                Return ResourceManager.GetString("colorBubblegum", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Cinnabar.
        '''</summary>
        Friend Shared ReadOnly Property colorCinnabar() As String
            Get
                Return ResourceManager.GetString("colorCinnabar", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Cinnamon.
        '''</summary>
        Friend Shared ReadOnly Property colorCinnamon() As String
            Get
                Return ResourceManager.GetString("colorCinnamon", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Cobalt.
        '''</summary>
        Friend Shared ReadOnly Property colorCobalt() As String
            Get
                Return ResourceManager.GetString("colorCobalt", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Colorized.
        '''</summary>
        Friend Shared ReadOnly Property colorColorized() As String
            Get
                Return ResourceManager.GetString("colorColorized", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Cyan.
        '''</summary>
        Friend Shared ReadOnly Property colorCyan() As String
            Get
                Return ResourceManager.GetString("colorCyan", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Dark Blue.
        '''</summary>
        Friend Shared ReadOnly Property colorDarkBlue() As String
            Get
                Return ResourceManager.GetString("colorDarkBlue", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Dark Green.
        '''</summary>
        Friend Shared ReadOnly Property colorDarkGreen() As String
            Get
                Return ResourceManager.GetString("colorDarkGreen", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Deep Purple.
        '''</summary>
        Friend Shared ReadOnly Property colorDeeppurple() As String
            Get
                Return ResourceManager.GetString("colorDeeppurple", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Grass.
        '''</summary>
        Friend Shared ReadOnly Property colorGrass() As String
            Get
                Return ResourceManager.GetString("colorGrass", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Green.
        '''</summary>
        Friend Shared ReadOnly Property colorGreen() As String
            Get
                Return ResourceManager.GetString("colorGreen", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Grey.
        '''</summary>
        Friend Shared ReadOnly Property colorGrey() As String
            Get
                Return ResourceManager.GetString("colorGrey", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Gun Metal.
        '''</summary>
        Friend Shared ReadOnly Property colorGunmetal() As String
            Get
                Return ResourceManager.GetString("colorGunmetal", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Happy Orange.
        '''</summary>
        Friend Shared ReadOnly Property colorHappyOrange() As String
            Get
                Return ResourceManager.GetString("colorHappyOrange", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Lavender.
        '''</summary>
        Friend Shared ReadOnly Property colorLavender() As String
            Get
                Return ResourceManager.GetString("colorLavender", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Light Blue.
        '''</summary>
        Friend Shared ReadOnly Property colorLightBlue() As String
            Get
                Return ResourceManager.GetString("colorLightBlue", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Lilac.
        '''</summary>
        Friend Shared ReadOnly Property colorLilac() As String
            Get
                Return ResourceManager.GetString("colorLilac", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Navy.
        '''</summary>
        Friend Shared ReadOnly Property colorNavy() As String
            Get
                Return ResourceManager.GetString("colorNavy", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Night.
        '''</summary>
        Friend Shared ReadOnly Property colorNight() As String
            Get
                Return ResourceManager.GetString("colorNight", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Orange.
        '''</summary>
        Friend Shared ReadOnly Property colorOrange() As String
            Get
                Return ResourceManager.GetString("colorOrange", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Padawan.
        '''</summary>
        Friend Shared ReadOnly Property colorPadawan() As String
            Get
                Return ResourceManager.GetString("colorPadawan", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Purple.
        '''</summary>
        Friend Shared ReadOnly Property colorPurple() As String
            Get
                Return ResourceManager.GetString("colorPurple", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Red.
        '''</summary>
        Friend Shared ReadOnly Property colorRed() As String
            Get
                Return ResourceManager.GetString("colorRed", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Rose.
        '''</summary>
        Friend Shared ReadOnly Property colorRose() As String
            Get
                Return ResourceManager.GetString("colorRose", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Royal.
        '''</summary>
        Friend Shared ReadOnly Property colorRoyal() As String
            Get
                Return ResourceManager.GetString("colorRoyal", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Royal Blue.
        '''</summary>
        Friend Shared ReadOnly Property colorRoyalBlue() As String
            Get
                Return ResourceManager.GetString("colorRoyalBlue", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Sea.
        '''</summary>
        Friend Shared ReadOnly Property colorSea() As String
            Get
                Return ResourceManager.GetString("colorSea", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Silver.
        '''</summary>
        Friend Shared ReadOnly Property colorSilver() As String
            Get
                Return ResourceManager.GetString("colorSilver", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Sky.
        '''</summary>
        Friend Shared ReadOnly Property colorSky() As String
            Get
                Return ResourceManager.GetString("colorSky", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Slate.
        '''</summary>
        Friend Shared ReadOnly Property colorSlate() As String
            Get
                Return ResourceManager.GetString("colorSlate", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Steam Blue.
        '''</summary>
        Friend Shared ReadOnly Property colorSteamblue() As String
            Get
                Return ResourceManager.GetString("colorSteamblue", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Teal.
        '''</summary>
        Friend Shared ReadOnly Property colorTeal() As String
            Get
                Return ResourceManager.GetString("colorTeal", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Truffle.
        '''</summary>
        Friend Shared ReadOnly Property colorTruffle() As String
            Get
                Return ResourceManager.GetString("colorTruffle", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Violet.
        '''</summary>
        Friend Shared ReadOnly Property colorViolet() As String
            Get
                Return ResourceManager.GetString("colorViolet", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Viridian.
        '''</summary>
        Friend Shared ReadOnly Property colorViridian() As String
            Get
                Return ResourceManager.GetString("colorViridian", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Watermelon.
        '''</summary>
        Friend Shared ReadOnly Property colorWatermelon() As String
            Get
                Return ResourceManager.GetString("colorWatermelon", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Youtube Red.
        '''</summary>
        Friend Shared ReadOnly Property colorYoutubered() As String
            Get
                Return ResourceManager.GetString("colorYoutubered", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Backgrounds:.
        '''</summary>
        Friend Shared ReadOnly Property customBackground() As String
            Get
                Return ResourceManager.GetString("customBackground", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Colors:.
        '''</summary>
        Friend Shared ReadOnly Property customColor() As String
            Get
                Return ResourceManager.GetString("customColor", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Games Details Color:.
        '''</summary>
        Friend Shared ReadOnly Property customGameDetails() As String
            Get
                Return ResourceManager.GetString("customGameDetails", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Grid Fade:.
        '''</summary>
        Friend Shared ReadOnly Property customGridFade() As String
            Get
                Return ResourceManager.GetString("customGridFade", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Hover Effect in Friends:.
        '''</summary>
        Friend Shared ReadOnly Property customHoverFriends() As String
            Get
                Return ResourceManager.GetString("customHoverFriends", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Library Dividers:.
        '''</summary>
        Friend Shared ReadOnly Property customLibraryDividers() As String
            Get
                Return ResourceManager.GetString("customLibraryDividers", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Notifications Position:.
        '''</summary>
        Friend Shared ReadOnly Property customNotificationPosition() As String
            Get
                Return ResourceManager.GetString("customNotificationPosition", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Notifications Quantity:.
        '''</summary>
        Friend Shared ReadOnly Property customNotificationQuantity() As String
            Get
                Return ResourceManager.GetString("customNotificationQuantity", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Notifications Timer:.
        '''</summary>
        Friend Shared ReadOnly Property customNotificationTimer() As String
            Get
                Return ResourceManager.GetString("customNotificationTimer", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Overlay Background:.
        '''</summary>
        Friend Shared ReadOnly Property customOverlayBackground() As String
            Get
                Return ResourceManager.GetString("customOverlayBackground", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Themes:.
        '''</summary>
        Friend Shared ReadOnly Property customTheme() As String
            Get
                Return ResourceManager.GetString("customTheme", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to TitleBar Black:.
        '''</summary>
        Friend Shared ReadOnly Property customTitleBar() As String
            Get
                Return ResourceManager.GetString("customTitleBar", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Transparent Uninstalled:.
        '''</summary>
        Friend Shared ReadOnly Property customTransparentUninstalled() As String
            Get
                Return ResourceManager.GetString("customTransparentUninstalled", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Create.
        '''</summary>
        Friend Shared ReadOnly Property editorCreate() As String
            Get
                Return ResourceManager.GetString("editorCreate", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Font Color.
        '''</summary>
        Friend Shared ReadOnly Property editorFontColor() As String
            Get
                Return ResourceManager.GetString("editorFontColor", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Title.
        '''</summary>
        Friend Shared ReadOnly Property editorTitle() As String
            Get
                Return ResourceManager.GetString("editorTitle", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Error connecting.
        '''</summary>
        Friend Shared ReadOnly Property errorConnecting() As String
            Get
                Return ResourceManager.GetString("errorConnecting", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Error downloading file of the skin.
        '''</summary>
        Friend Shared ReadOnly Property errorDownloadingFile() As String
            Get
                Return ResourceManager.GetString("errorDownloadingFile", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Error extracting files.
        '''</summary>
        Friend Shared ReadOnly Property errorExtractingFiles() As String
            Get
                Return ResourceManager.GetString("errorExtractingFiles", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Error moving files.
        '''</summary>
        Friend Shared ReadOnly Property errorMovingFiles() As String
            Get
                Return ResourceManager.GetString("errorMovingFiles", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Error to registry in Windows.
        '''</summary>
        Friend Shared ReadOnly Property errorRegistryWindows() As String
            Get
                Return ResourceManager.GetString("errorRegistryWindows", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Error starting download, try again.
        '''</summary>
        Friend Shared ReadOnly Property errorStartingDownload() As String
            Get
                Return ResourceManager.GetString("errorStartingDownload", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Extracting files.
        '''</summary>
        Friend Shared ReadOnly Property extractingFiles() As String
            Get
                Return ResourceManager.GetString("extractingFiles", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Instructions to install fonts.txt.
        '''</summary>
        Friend Shared ReadOnly Property fontsFile() As String
            Get
                Return ResourceManager.GetString("fontsFile", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to INSTALL THESE FONTS.
        '''</summary>
        Friend Shared ReadOnly Property fontsFolder() As String
            Get
                Return ResourceManager.GetString("fontsFolder", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Select the file with extension .ttf.
        '''</summary>
        Friend Shared ReadOnly Property fontsInstructions1() As String
            Get
                Return ResourceManager.GetString("fontsInstructions1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Do right click in the font and select install.
        '''</summary>
        Friend Shared ReadOnly Property fontsInstructions2() As String
            Get
                Return ResourceManager.GetString("fontsInstructions2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Change language:.
        '''</summary>
        Friend Shared ReadOnly Property gridOptionsLanguageLabel() As String
            Get
                Return ResourceManager.GetString("gridOptionsLanguageLabel", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Warning: If you change the language all the installed skins will be delete.
        '''</summary>
        Friend Shared ReadOnly Property gridOptionsLanguageLabelWarning() As String
            Get
                Return ResourceManager.GetString("gridOptionsLanguageLabelWarning", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Select Skin:.
        '''</summary>
        Friend Shared ReadOnly Property labelTopBarComboBox() As String
            Get
                Return ResourceManager.GetString("labelTopBarComboBox", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Skin in Use:.
        '''</summary>
        Friend Shared ReadOnly Property labelTopBarSkinUse() As String
            Get
                Return ResourceManager.GetString("labelTopBarSkinUse", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Steam Folder:.
        '''</summary>
        Friend Shared ReadOnly Property labelTopBarSteamFolder() As String
            Get
                Return ResourceManager.GetString("labelTopBarSteamFolder", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Contact.
        '''</summary>
        Friend Shared ReadOnly Property menuContact() As String
            Get
                Return ResourceManager.GetString("menuContact", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Editor.
        '''</summary>
        Friend Shared ReadOnly Property menuEditor() As String
            Get
                Return ResourceManager.GetString("menuEditor", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Options.
        '''</summary>
        Friend Shared ReadOnly Property menuOptions() As String
            Get
                Return ResourceManager.GetString("menuOptions", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Moving files.
        '''</summary>
        Friend Shared ReadOnly Property movingFiles() As String
            Get
                Return ResourceManager.GetString("movingFiles", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to No.
        '''</summary>
        Friend Shared ReadOnly Property no() As String
            Get
                Return ResourceManager.GetString("no", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Bottom Left.
        '''</summary>
        Friend Shared ReadOnly Property positionBottomLeft() As String
            Get
                Return ResourceManager.GetString("positionBottomLeft", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Bottom Right.
        '''</summary>
        Friend Shared ReadOnly Property positionBottomRight() As String
            Get
                Return ResourceManager.GetString("positionBottomRight", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Top Left.
        '''</summary>
        Friend Shared ReadOnly Property positionTopLeft() As String
            Get
                Return ResourceManager.GetString("positionTopLeft", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Top Right.
        '''</summary>
        Friend Shared ReadOnly Property positionTopRight() As String
            Get
                Return ResourceManager.GetString("positionTopRight", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Progress download:.
        '''</summary>
        Friend Shared ReadOnly Property progressDownload() As String
            Get
                Return ResourceManager.GetString("progressDownload", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Searching download.
        '''</summary>
        Friend Shared ReadOnly Property searchingDownload() As String
            Get
                Return ResourceManager.GetString("searchingDownload", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Install.
        '''</summary>
        Friend Shared ReadOnly Property skinInstallButton() As String
            Get
                Return ResourceManager.GetString("skinInstallButton", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Install Again.
        '''</summary>
        Friend Shared ReadOnly Property skinInstallButtonAgain() As String
            Get
                Return ResourceManager.GetString("skinInstallButtonAgain", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Skin installed.
        '''</summary>
        Friend Shared ReadOnly Property skinInstalled() As String
            Get
                Return ResourceManager.GetString("skinInstalled", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Starting Steam.
        '''</summary>
        Friend Shared ReadOnly Property startingSteam() As String
            Get
                Return ResourceManager.GetString("startingSteam", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to You have installed the last version.
        '''</summary>
        Friend Shared ReadOnly Property succesfulLastVersion() As String
            Get
                Return ResourceManager.GetString("succesfulLastVersion", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Created by:.
        '''</summary>
        Friend Shared ReadOnly Property tabControlAutorCreado() As String
            Get
                Return ResourceManager.GetString("tabControlAutorCreado", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Donate:.
        '''</summary>
        Friend Shared ReadOnly Property tabControlAutorDonar() As String
            Get
                Return ResourceManager.GetString("tabControlAutorDonar", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Author.
        '''</summary>
        Friend Shared ReadOnly Property tabControlAutorLabel() As String
            Get
                Return ResourceManager.GetString("tabControlAutorLabel", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Customization.
        '''</summary>
        Friend Shared ReadOnly Property tabControlCustomizationLabel() As String
            Get
                Return ResourceManager.GetString("tabControlCustomizationLabel", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Screenshots.
        '''</summary>
        Friend Shared ReadOnly Property tabControlScreenshotsLabel() As String
            Get
                Return ResourceManager.GetString("tabControlScreenshotsLabel", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Do double click and the screenshoot will expand.
        '''</summary>
        Friend Shared ReadOnly Property tabControlScreenshotsTooltip() As String
            Get
                Return ResourceManager.GetString("tabControlScreenshotsTooltip", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Dark.
        '''</summary>
        Friend Shared ReadOnly Property themeDark() As String
            Get
                Return ResourceManager.GetString("themeDark", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Light.
        '''</summary>
        Friend Shared ReadOnly Property themeLight() As String
            Get
                Return ResourceManager.GetString("themeLight", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Updating new version of.
        '''</summary>
        Friend Shared ReadOnly Property updatingNewVersion() As String
            Get
                Return ResourceManager.GetString("updatingNewVersion", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Web.
        '''</summary>
        Friend Shared ReadOnly Property web() As String
            Get
                Return ResourceManager.GetString("web", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Yes.
        '''</summary>
        Friend Shared ReadOnly Property yes() As String
            Get
                Return ResourceManager.GetString("yes", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
